apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: nginx
data:
  index.html: |
    <html>
    <head><title>Welcome to Nginx!</title></head>
    <body><h1>Hello from Nginx on Kubernetes!</h1></body>
    </html>
